### ISSUE TITLE
As a User I should be able to signup into the system

### ISSUE THREAD

**Issue by pwalvarado** [pwalvarado/sidekiq-workshop#5]
**Use devise for authentication**
- [x] devise configuration (routes)
- [x] add user model #16
- [ ] add :[registerable and :confirmable to Users](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users) #17
- [ ] add sign up, sign in on root page #18 
- [ ] add logout and edit profile links on navbar #19 
- [x] add before action authenticate validation #20 
- [ ] tweak css for devise authentication #21
